---
abstract: 'a markdown notetaker'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Notetaker
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Zip: '0'
  Carp: '0'
  Crypt::Passphrase: '0'
  Crypt::Passphrase::Argon2: '0'
  Date::Period::Human: '0'
  File::Basename: '0'
  File::Temp: '0'
  Getopt::Long: '0'
  Markdown::Perl: '0'
  Mojo::Base: '0'
  Mojo::File: '0'
  Mojo::URL: '0'
  Mojolicious: '8'
  Mojolicious::Lite: '0'
  Mojolicious::Plugin::Authentication: '0'
  Mojolicious::Plugin::HTMX: '0'
  Mojolicious::Static::Role::Compressed: '0'
  Moo: '2'
  PerlX::Maybe: '0'
  Text::CleanFragment: '0'
  Text::FrontMatter::YAML: '0.06'
  Text::HTML::Turndown: '0'
  YAML::PP::LibYAML: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/App-Notetaker/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/App-Notetaker.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
